### ISSUE TITLE
cannot start bigdataserver

### ISSUE THREAD

**Issue by xulman** [bigdataviewer/bigdataviewer-server#6]
Hi there,
I'm having troubles starting BDS on my own:

# option 1

When I tried `mvn package`, it created .jar file nicely.
However, already a plain attempt to "execute" the .jar failed saying
```
$> java -jar target/bigdataviewer-server-2.1.1-SNAPSHOT.jar
no main manifest attribute, in target/bigdataviewer-server-2.1.1-SNAPSHOT.jar
```
Tobi adds to it: "IIRC, I didn’t package the bigdataserver.jar with maven at all, but with eclipse.
So that would explain, why there is no main class defined if you use “mvn package”."

It does however run fine when started from IDE (IntelliJ).

# option 2

`wget http://fly.mpi-cbg.de/~pietzsch/bigdataserver.jar`, and start it, e.g.,
`java -jar bigdataserver.jar TRIFvideo /absolute/path/to/some/dataset.xml` fails saying
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more
```
Actually, the very same error occurs when executed just as `java -jar bigdataserver.jar`

# Java version:

```
$> java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-suse-lp151.3.12.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.6+10-suse-lp151.3.12.1-x8664, mixed mode)
```

Vlado

**Comment by tpietzsch** [comment]
Hi Vlado

> Tobi adds to it: "IIRC, I didn’t package the bigdataserver.jar with maven at all, but with eclipse.
> So that would explain, why there is no main class defined if you use “mvn package”."

I did some updates, and you can now build a "fat jar" with
```
mvn clean package -P fatjar
```

**Comment by xulman** [comment]
Thank you for fixing it!
Best regards,
Vlado
